SELECT CASE 
    WHEN GRADES.GRADE >= 8 THEN STUDENTS.NAME ELSE NULL END AS NAMES,
    GRADES.GRADE,
    STUDENTS.MARKS
FROM STUDENTS
JOIN GRADES
    ON STUDENTS.MARKS BETWEEN GRADES.MIN_MARK AND GRADES.MAX_MARK
ORDER BY 
    GRADES.GRADE DESC,
    NAMES,
    STUDENTS.MARKS;