SELECT
    HACKERS.HACKER_ID,
    HACKERS.NAME
FROM SUBMISSIONS
JOIN CHALLENGES
    ON SUBMISSIONS.CHALLENGE_ID = CHALLENGES.CHALLENGE_ID
JOIN DIFFICULTY
    ON CHALLENGES.DIFFICULTY_LEVEL = DIFFICULTY.DIFFICULTY_LEVEL
JOIN HACKERS
    ON SUBMISSIONS.HACKER_ID = HACKERS.HACKER_ID
        AND SUBMISSIONS.SCORE = DIFFICULTY.SCORE
GROUP BY
    HACKERS.HACKER_ID,
    HACKERS.NAME
HAVING COUNT(SUBMISSIONS.HACKER_ID)  > 1
ORDER BY 
    COUNT(SUBMISSIONS.HACKER_ID) DESC,
    HACKER_ID;