SELECT
    C.COMPANY_CODE,
    C.FOUNDER,
    COUNT(DISTINCT L.LEAD_MANAGER_CODE) AS LEAD_MANAGER_COUNT,
    COUNT(DISTINCT S.SENIOR_MANAGER_CODE) AS SENIOR_MANAGER_COUNT,
    COUNT(DISTINCT M.MANAGER_CODE) AS MANAGER_COUNT,
    COUNT(DISTINCT E.EMPLOYEE_CODE) AS EMPLOYEE_COUNT
FROM COMPANY AS C
INNER JOIN LEAD_MANAGER L
    ON C.COMPANY_CODE = L.COMPANY_CODE
INNER JOIN SENIOR_MANAGER AS S
    ON C.COMPANY_CODE = S.COMPANY_CODE
INNER JOIN MANAGER AS M
    ON C.COMPANY_CODE = M.COMPANY_CODE
INNER JOIN EMPLOYEE AS E
    ON C.COMPANY_CODE = E.COMPANY_CODE
GROUP BY 
    C.COMPANY_CODE,
    C.FOUNDER
ORDER BY C.COMPANY_CODE;
