--METHOD 1
WITH cte AS ( 
  SELECT
    ROW_NUMBER() OVER (
      PARTITION BY OCCUPATION 
      ORDER BY NAME) AS ROW_NUMBER, 
    CASE WHEN OCCUPATION ='Doctor' THEN NAME ELSE NULL END AS DOCTOR,
    CASE WHEN OCCUPATION ='Professor' THEN NAME ELSE NULL END AS PROFESSOR,
    CASE WHEN OCCUPATION = 'Singer' THEN NAME ELSE NULL END AS SINGER,
    CASE WHEN OCCUPATION ='Actor' THEN NAME ELSE NULL END AS ACTOR  
FROM OCCUPATIONS
)
SELECT 
    MIN(DOCTOR),
    MIN(PROFESSOR),
    MIN(SINGER),
    MIN(ACTOR)
FROM cte
GROUP BY ROW_NUMBER;
--METHOD 2
SELECT 
    MIN(DOCTOR),
    MIN(PROFESSOR),
    MIN(SINGER),
    MIN(ACTOR)
FROM ( 
  SELECT
    ROW_NUMBER() OVER (
      PARTITION BY OCCUPATION 
      ORDER BY NAME) AS RANK, 
    CASE WHEN OCCUPATION ='Doctor' THEN NAME ELSE NULL END AS DOCTOR,
    CASE WHEN OCCUPATION ='Professor' THEN NAME ELSE NULL END AS PROFESSOR,
    CASE WHEN OCCUPATION = 'Singer' THEN NAME ELSE NULL END AS SINGER,
    CASE WHEN OCCUPATION ='Actor' THEN NAME ELSE NULL END AS ACTOR  
FROM OCCUPATIONS
) AS MYTABLE
GROUP BY ROW_NUMBER;